var getSchedule = function(schedule) {
    var timerObjects;

    if (schedule === 'standard') {

        timerObjects = [
            {
                startTimeHour: 9,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Stand-up'
            }, {
                startTimeHour: 9,
                startTimeMinute: 30,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 9,
                startTimeMinute: 55,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 10,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 10,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 10,
                startTimeMinute: 30,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 10,
                startTimeMinute: 55,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 11,
                startTimeMinute: 05,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 11,
                startTimeMinute: 30,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 11,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 12,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Lunch'
            }, {
                startTimeHour: 13,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 13,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 13,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 14,
                startTimeMinute: 00,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 14,
                startTimeMinute: 10,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 14,
                startTimeMinute: 35,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 14,
                startTimeMinute: 45,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 15,
                startTimeMinute: 10,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 15,
                startTimeMinute: 25,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 15,
                startTimeMinute: 50,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 16,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 16,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 16,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 17,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Home'
            }, {
                startTimeHour: 25,
                startTimeMinute: 00,
                colorBackground: 'pink',
                statusName: 'crazylunch'
            }
        ];

    } else if (schedule === 'tuesday') {

        timerObjects = [
            {
                startTimeHour: 9,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Stand-up'
            }, {
                startTimeHour: 9,
                startTimeMinute: 30,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 9,
                startTimeMinute: 55,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 10,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 10,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 10,
                startTimeMinute: 30,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 10,
                startTimeMinute: 55,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 11,
                startTimeMinute: 05,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 11,
                startTimeMinute: 30,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 11,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 12,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Lunch'
            }, {
                startTimeHour: 13,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 13,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 13,
                startTimeMinute: 30,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 13,
                startTimeMinute: 55,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 14,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 14,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 14,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 15,
                startTimeMinute: 00,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 15,
                startTimeMinute: 05,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 15,
                startTimeMinute: 30,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 15,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 16,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Best Practices'
            }, {
                startTimeHour: 17,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Home'
            }, {
                startTimeHour: 25,
                startTimeMinute: 00,
                colorBackground: 'pink',
                statusName: 'crazylunch'
            }
        ];


    }else if (schedule === 'friday') {

        timerObjects = [
            {
                startTimeHour: 9,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Stand-up'
            }, {
                startTimeHour: 9,
                startTimeMinute: 30,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 9,
                startTimeMinute: 55,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 10,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 10,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 10,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 11,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Read a book'
            }, {
                startTimeHour: 12,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Lunch'
            }, {
                startTimeHour: 13,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 13,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 13,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 14,
                startTimeMinute: 00,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 14,
                startTimeMinute: 10,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 14,
                startTimeMinute: 35,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 14,
                startTimeMinute: 45,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 15,
                startTimeMinute: 10,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 15,
                startTimeMinute: 25,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 15,
                startTimeMinute: 50,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 16,
                startTimeMinute: 00,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 16,
                startTimeMinute: 25,
                colorBackground: 'green',
                statusName: 'Availible'
            }, {
                startTimeHour: 16,
                startTimeMinute: 35,
                colorBackground: 'red',
                statusName: 'Pomodoro'
            }, {
                startTimeHour: 17,
                startTimeMinute: 00,
                colorBackground: 'blue',
                statusName: 'Home'
            }, {
                startTimeHour: 25,
                startTimeMinute: 00,
                colorBackground: 'pink',
                statusName: 'crazylunch'
            }
        ];

    }


    return timerObjects;
};